edition = "2021"
max_width = 100
use_small_heuristics = "Default"
tab_spaces = 4
newline_style = "Unix"
use_field_init_shorthand = true
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
use_try_shorthand = true
force_explicit_abi = true